molecule: Avoid regression with ansible-core 2.17.0
SyntaxError: future feature annotations is not defined
[...]
The following modules failed to execute: ansible.legacy.setup